package test.adf.kerberos.am.client;

import oracle.jbo.client.remote.ApplicationModuleImpl;

import test.adf.kerberos.am.common.MainAppModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Apr 19 19:12:01 GMT+03:00 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MainAppModuleClient extends ApplicationModuleImpl implements MainAppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public MainAppModuleClient() {
    }

    public void disconnect() {
        Object _ret = this.riInvokeExportedMethod(this,"disconnect",null,null);
        return;
    }
}
