package test.adf.kerberos.am.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Apr 19 19:12:01 GMT+03:00 2018
// ---------------------------------------------------------------------
public interface MainAppModule extends ApplicationModule {
    void disconnect();
}
