package test.adf.kerberos.am;

import oracle.jbo.ApplicationModule;
import oracle.jbo.Session;
import oracle.jbo.server.ApplicationModuleImpl;

import test.adf.kerberos.view.LogonUserViewImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Apr 18 16:05:56 GMT+03:00 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleModuleImpl extends ApplicationModuleImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleModuleImpl() {
    }

    /**
     * Container's getter for LogonUser.
     * @return LogonUser
     */
    public LogonUserViewImpl getLogonUser() {
        return (LogonUserViewImpl)findViewObject("LogonUser");
    }

    protected void prepareSession(Session session) {
        super.prepareSession(session);
        setReleaseLevel (ApplicationModule.RELEASE_LEVEL_RESERVED);
    }
}
