package test.adf.kerberos.view;

import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;

// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Apr 18 12:42:45 MSK 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class LogonUserViewRowImpl extends ViewRowImpl {

    /**
     * This is the default constructor (do not remove).
     */
    public LogonUserViewRowImpl() {
    }
}

