package test.adf.kerberos.view;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Apr 18 12:42:45 MSK 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class LogonUserViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public LogonUserViewImpl() {
    }
}

